# fly.toml app configuration file generated for seull1-blog-small-dawn-4305 on 2024-02-16T02:20:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seull1-blog-small-dawn-4305'
primary_region = 'nrt'



[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
